language: node_js
sudo: false
addons:
  firefox: latest
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
node_js:
  - '4.1'
before_script:
  - 'export DISPLAY=:99.0'
  - sh -e /etc/init.d/xvfb start
  - sleep 3
  - git config --global user.email "chuckh@hware.com"
  - git config --global user.name "Travis-CI"
  - npm i -g bower gulp
  - bower i
script:
  - ./travis-runner.sh
env:
  global:
    secure: Pw4Q3FbwflA3O+v0ZKTaKZ80gGPIS/+bquAax+UejUliTaZiWJjyIB0lsHMQfSr8dzRRv2DT4+r+9N1n8pDbc0xxbSPZVIIw4bI76LHb3SYYJFRl+kkjwcwICDFn8cnk2BX/YsbWSI3d3ml87yqqVzbiX0hmJUbt/hYfxq98ZcqxZT374/UN7iWcuOq5lGgec9mOnUwjn0sOXf8k8YRi+bTCMK3ccGvlzIrE4/2p8P3HQWO3Xe6CqTLg7rmxIuTqwfX5RUlqcPqVzFpHhrNR9nWKokOFBi6F0jPUzJQowfBI/sE5PfM+/anXCwZZl+KzIXN+SwKnFawvq3/opd47LsM8XeGSuP23ry96lUfa4JZ7ZtLMbaF48PseU3LA999RqWeC2hxnrZeCTVbEtkHJVSHSy7s0PfdBuSqYIHAfInil9Y6sXwo08jnr9KzVFsn0SFdNjM320Zl9Yrnw2OqBjuEWqfmj2WqV5bEqCN5qTa/sdHhcQ0MTQXZSX0cDrAuxqdbF2uuaIbihoAAoJczy6HXLTuhYrW/r4OfgjQQTn2DqTUUQ3J7eKUKk+lOMGEz9eV7PZ7m0ngURjElmZt2zbR6lhz3iR6EXsMhrgyroGZc0bkNGvlrDo2ISlyiV5BEInsNUtDXsXUzvvHviK70MCnwuJ2Q6mSjb3Ty6dKNIsvM=
